### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.51xuecheng.cn
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=snLfOX&redirect_uri=http://www.51xuecheng.cn


#POST {{auth_host}}/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=zhangsan&password=123


### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=stu1&password=111111

###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjcmVhdGVUaW1lXCI6XCIyMDIzLTA1LTE0VDE0OjUxOjI2XCIsXCJpZFwiOlwiYTQwMjIyOGEtYmM4ZS00Y2I5LTlmMDctNzNiNDMxZGU3ZDgyXCIsXCJuYW1lXCI6XCLotbDov4fkurrpl7RcIixcIm5pY2tuYW1lXCI6XCLotbDov4fkurrpl7RcIixcInBlcm1pc3Npb25zXCI6W10sXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJvNVBCMXN5cW1sM0F0Vi1IYW5DUWY5bnFZNDFNXCIsXCJ1dHlwZVwiOlwiMTAxMDAxXCIsXCJ3eFVuaW9uaWRcIjpcIm81UEIxc3lxbWwzQXRWLUhhbkNRZjlucVk0MU1cIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjg0MDU3OTA0LCJhdXRob3JpdGllcyI6WyJ4Y19zeXNtYW5hZ2VyX2RvYyIsInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfbGlzdCIsInhjX3N5c21hbmFnZXIiLCJ4Y19zeXNtYW5hZ2VyX2NvbXBhbnkiLCJ4Y19zeXNtYW5hZ2VyX2xvZyJdLCJqdGkiOiJiZTlmOGZhZC1jODBmLTRiYTctYjc3Ni03ZTY4MzUwNjJlMTEiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.xNyyApD8TfcliEPv_4lR8xWddx8s0ZG9ekgV6ywIEsU